name: Identity Service CI/CD

on:
  push:
    branches: [ "main", "master" ]
    paths:
      # Rutas actualizadas
      - 'TiendaInspireIdentity/**'
      - 'TiendaInspire.ServiceDefaults/**'
      - 'TiendaInspire.Shared/**'
      - '.github/workflows/identity-docker.yml' 
  pull_request:
    branches: [ "main", "master" ]
    paths:
      # Rutas actualizadas
      - 'TiendaInspireIdentity/**'
      - 'TiendaInspire.ServiceDefaults/**'
      - 'TiendaInspire.Shared/**'
      - '.github/workflows/identity-docker.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/identity-api-image

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
         
          file: ./TiendaInspireIdentity/Dockerfile
          push: true
          load: true
          tags: identity-api:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

